---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
  - name: in this task , i want to install apache2 server
    apt:
       name: apache2
       state: present
    when: ansible_os_family== "Debian"
       
  - name: in this task, i want to start webserver
    service:
       name: apache2
       state: started
    when: ansible_os_family== "Debian"

  - name: in this task, i want to install httpd on redhat
    dnf:
       name: httpd
       state: present
    when: ansible_os_family== "RedHat"
  - name: in this task, i want to start webserver on redhat
    service:
       name: httpd
       state: started
    when: ansible_os_family== "RedHat"
    